# TODO: I am not sure that we want to use the admin user, Won't be available initially...
[web]
myapp-prod ansible_host=203.0.113.42 ansible_user={{ admin_user }} ansible_port={{ ssh_port }}

# For a single-server deployment, the same host appears in both web and db. If you split
# DB onto its own box (or use managed Postgres), change this.
[db]
myapp-prod ansible_host=203.0.113.42 ansible_user={{ admin_user }} ansible_port={{ ssh_port }}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
