# Generated by Django 6.0.3 on 2026-05-26 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_categoryscore"),
        ("assessments", "0002_assessment_client"),
        ("reports", "0003_feedback_fields_categoryfeedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="overall_text",
            new_name="report_feedback",
        ),
        migrations.CreateModel(
            name="CategorySection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("overview", models.TextField()),
                ("impact", models.TextField()),
                ("path_forward", models.TextField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_sections",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_sections",
                        to="assessments.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("analysis", "category")},
            },
        ),
        migrations.CreateModel(
            name="ExecutiveSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_summaries",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("analysis",)},
            },
        ),
        migrations.DeleteModel(
            name="ReportSection",
        ),
    ]
