# Generated by Django 6.0.3 on 2026-05-26 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_categoryscore"),
        ("reports", "0006_category_recommendations"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationsOverview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_overviews",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("analysis",)},
            },
        ),
    ]
