# Generated by Django 6.0.3 on 2026-05-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_categoryscore"),
        ("reports", "0008_roadmap"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roadmap",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmaps",
                to="analysis.analysis",
                unique=True,
            ),
        ),
    ]
