# Generated by Django 6.0.3 on 2026-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_alter_roadmap_unique_together_alter_roadmap_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmap",
            name="closing_reflections",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="post_implementation_outcomes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="potential_challenges",
            field=models.TextField(),
        ),
    ]
