# Generated by Django 6.0.3 on 2026-05-11 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("assessments", "0002_assessment_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "max_possible_score",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_scores",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_scores",
                        to="assessments.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("analysis", "category")},
            },
        ),
    ]
