# Generated by Django 6.0.3 on 2026-04-07 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="client",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="clients.client",
            ),
            preserve_default=False,
        ),
    ]
