# Generated by Django 6.0.3 on 2026-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_assessment_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="name",
            field=models.CharField(default="Initial Report", max_length=100),
        ),
    ]
