# Generated by Django 6.0.3 on 2026-09-10 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_backfill_assessment_status_and_guidance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAccessLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[("guidance", "Guidance"), ("answer", "Answer")],
                        max_length=10,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_access_links",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment", "link_type")},
            },
        ),
    ]
