# Generated by Django 6.0.3 on 2026-04-06 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("automotive", "Automotive"),
                            ("construction", "Construction"),
                            ("education", "Education"),
                            ("energy_utilities", "Energy & Utilities"),
                            ("finance", "Finance & Banking"),
                            ("food_beverage", "Food & Beverage"),
                            ("government", "Government & Public Sector"),
                            ("healthcare", "Healthcare & Life Sciences"),
                            ("hospitality", "Hospitality & Tourism"),
                            ("insurance", "Insurance"),
                            ("legal", "Legal Services"),
                            ("logistics", "Logistics & Transportation"),
                            ("manufacturing", "Manufacturing"),
                            ("media", "Media & Entertainment"),
                            ("nonprofit", "Non-Profit & NGO"),
                            ("professional_services", "Professional Services"),
                            ("real_estate", "Real Estate"),
                            ("retail", "Retail & E-Commerce"),
                            ("technology", "Technology & Software"),
                            ("telecommunications", "Telecommunications"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
