# Generated by Django 6.0.3 on 2026-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_company_size_alter_client_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
